### ISSUE TITLE
Partial application

### ISSUE THREAD

**Issue by maksimf** [MostlyAdequate/mostly-adequate-guide-ru#10]
@DrBoolean While translating I've noticed that you write "See how we partially applied `replace`" here:

https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch5.md#pointfree

Code:

```
compose(replace(/\s+/ig, '_'), toLowerCase)
```

But are you really partially applying function here? As it takes 2 arguments and you composing it with 2 arguments as well. Did I get something wrong?

**Comment by maksimf** [comment]
Maybe you meant that `replace` and `toLowerCase` are lacking object, is this called partial application as well?

**Comment by DrBoolean** [comment]
Hi @maksimf 

I'm using the `replace` defined here: https://github.com/MostlyAdequate/mostly-adequate-guide/blob/master/ch4.md#cant-live-if-livin-is-without-you (second code block).

The third argument is the object `str`, which technically can be thought of as the object and not an argument (thinking in python terms). I'm keeping it simple and treating it like any other argument though.

I still need to convert all examples to ramda (http://ramdajs.com/0.17/docs/#replace) which would make everything less ambiguous.

**Comment by maksimf** [comment]
@DrBoolean thank you, now it's clear :+1:
