### ISSUE TITLE
Common agreement in Russian translations

### ISSUE THREAD

**Issue by zefirka** [MostlyAdequate/mostly-adequate-guide-ru#11]
I've got question, or suggestion. I'm going to translate 6th chapter. There are a bunch of different Russian translations for common functional programming terminology, so I think, maybe we should create common agreements how to translate terminology. For example word "application" can be - приложение, применение, аппликация. 

Don't you think that we need common agreements?

**Comment by maksimf** [comment]
Yes, it would be great to have these agreements. We can discuss them in this PR
