### ISSUE TITLE
Глава 4 Каррирование

### ISSUE THREAD

**Issue by MrEfrem** [MostlyAdequate/mostly-adequate-guide-ru#19]
Упражнения, бонус 2.
В оригинале задача звучит совсем не так как переведено и в оригинале есть пример того что надо получить.

Оригинал:
// Bonus 2:
// ============
// Use slice to define a function "take" that takes n elements from the beginning of the string. Make it curried.
// // Result for "Something" with n=4 should be "Some"

Перевод:
// Бонус 2:
// ============
// используйте метод slice, чтобы объявить функцию "take", которая принимает n аргументов. Сделайте её каррируемой

**Comment by maksimf** [comment]
Спасибо, поправил

**Comment by MrEfrem** [comment]
Всегда пожалуйста.
А перевод дальнейших глав планируется? Мне кажется что с монадами поди сложно будет разобраться в иноязычной форме.

**Comment by maksimf** [comment]
Планируется, пока просто тяжко со временем, но книжку надо добить
