### ISSUE TITLE
Не генерируется pdf, epub

### ISSUE THREAD

**Issue by Vsnegovik** [MostlyAdequate/mostly-adequate-guide-ru#77]
Выполняю по инструкции 
`npm run setup`

```
"$" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mostly-adequate-guide@1.0.0 setup: `$(npm bin)/gitbook install`
npm ERR! Exit status 1
```

OS: Windows 10

**Comment by maksimf** [comment]
Легче всего это обойти собрав книгу под *nix-системой. Но если под виндой у вас стоит `gitbook`, то попробуйте просто запустить `gitbook install`

**Comment by Vsnegovik** [comment]
Спасибо за совет, разобрался со всеми сложностями и составил инструкцию. Понимаю, что на linux проще работать с такими вещами, но мне понадобилось cобрать книгу именно с windows. Надеюсь, что моя инструкция будет полезна.

**Comment by maksimf** [comment]
Спасибо
