### ISSUE TITLE
Глава 13

### ISSUE THREAD

**Issue by maksimf** [MostlyAdequate/mostly-adequate-guide-ru#83]
@VladimirLogachev @Sakayama не хотите ли перевести?

**Comment by vladimirlogachev** [comment]
Хотим. 
Скажу так: либо переведём к концу мая, либо у нас нет времени.

**Comment by maksimf** [comment]
Спасибо!

**Comment by vladimirlogachev** [comment]
Подтянул изменения из оригинала, сделал PR, понемногу перевожу.

**Comment by vladimirlogachev** [comment]
Максим, давай заведём 2 лейбла для issues: "Обсуждение" и "Задача", и уберём эти Not an issue, и обсуждения оставим висеть, а задачи будем закрывать по мере работы. Норм?

**Comment by maksimf** [comment]
Ага

**Comment by vladimirlogachev** [comment]
Я в организации есть, а прав у меня нет (Brian забыл, а мне не к спеху). Короче, я админить не могу ничего.

**Comment by maksimf** [comment]
Вроде пригласил
