### ISSUE TITLE
Глава 3

### ISSUE THREAD

**Issue by fruit765** [MostlyAdequate/mostly-adequate-guide-ru#86]
Вроде как написано "чистая функция должна быть честной в отношении своих зависимостей", а как же зависимость от других функций? Или на функции это не распространяется? Здесь функция чистая
const signUp = (Db, Email, attrs) => () => {
  const user = saveUser(Db, attrs);
  welcomeUser(Email, user);
};
Но является ли это чистой функцией? Это скорее процедура
() => {
  const user = saveUser(Db, attrs);
  welcomeUser(Email, user);
}

**Comment by maksimf** [comment]
```
Чистая функция — это функция, которая при одинаковых значениях аргументов всегда возвращает одинаковые значения и не имеет наблюдаемых побочных эффектов
```

В первом случае функция `signUp` для одних и тех же значений аргументов всегда будет возвращать одно и то же значение — функцию, которая, в свою очередь, уже обладает побочными эффектами (не чистая)
